# Generated by Django 3.1.7 on 2021-03-24 18:19

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data',
            field=django_cryptography.fields.encrypt(models.BinaryField(unique=True)),
        ),
    ]
