name: hello
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install django
        run: pip install django
      - name: makemigration
        run: python3 manage.py makemigrations LegacySite
      - name: migrate
        run: python3 manage.py migrate
      - name: test
        run: python3 manage.py test
        
