name: hello
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install django
        run: pip install django
      - name: install dotenv
        run:  pip install -U python-dotenv
      - name: install cryptography
        run: pip install django-cryptography
      - name: makemigration
        run: python3 manage.py makemigrations LegacySite
      - name: migrate
        run: python3 manage.py migrate
      - name: test
        run: python3 manage.py test
        
